

export const CategoryConstants = {
  GET_CAT_REQUEST: ' GET_CAT_REQUEST',
  GET_CAT_SUCCESS: 'GET_CAT_SUCCESS',
  GET_CAT_FAILURE: 'GET_CAT_FAILURE',
  ADD_NEW_CAT_REQUEST: 'ADD_NEW_CAT_REQUEST',
  ADD_NEW_CAT_SUCCESS: 'ADD_NEW_CAT_SUCCESS',
  ADD_NEW_CAT_FAILURE: 'ADD_NEW_CAT_FAILURE',
}

export const ProductConstants = {
  GET_PRODUCTS_BYSLUG: 'GET_PRODUCTS_BYSLUG',
  GET_PRODUCT_PAGE_REQUEST: 'GET_PRODUCT_PAGE_REQUEST',
  GET_PRODUCT_PAGE_SUCCESS: 'GET_PRODUCT_PAGE_SUCCESS',
  GET_PRODUCT_PAGE_FAILURE: 'GET_PRODUCT_PAGE_FAILURE',

  GET_PRODUCT_DETAILS_REQUEST: 'GET_PRODUCT_DETAILS_REQUEST',
  GET_PRODUCT_DETAILS_SUCCESS: 'GET_PRODUCT_DETAILS_SUCCESS',
  GET_PRODUCT_DETAILS_FAILURE: 'GET_PRODUCT_DETAILS_FAILURE',
}

export const AuthConstants = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'LOGOUT_FAILURE'
}