export const authConstants = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_FAILURE: 'LOGOUT_FAILURE',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
}

export const userConstants = {
  USER_REG_REQUEST: 'USER_REG_REQUEST',
  USER_REG_SUCCESS: 'USER_REG_SUCCESS',
  USER_REG_FAILURE: 'USER_REG_FAILURE'


}

export const CategoryConstants = {
  GET_CAT_REQUEST: ' GET_CAT_REQUEST',
  GET_CAT_SUCCESS: 'GET_CAT_SUCCESS',
  GET_CAT_FAILURE: 'GET_CAT_FAILURE',
  ADD_NEW_CAT_REQUEST: 'ADD_NEW_CAT_REQUEST',
  ADD_NEW_CAT_SUCCESS: 'ADD_NEW_CAT_SUCCESS',
  ADD_NEW_CAT_FAILURE: 'ADD_NEW_CAT_FAILURE',
}

export const productConstants={
  GET_PRODUCT_REQ: 'GET_PRODUCT_REQ',
  GET_PRODUCT_SUCCESS: 'GET_PRODUCT_SUCCESS',
  GET_PRODUCT_FAILURE: 'GET_PRODUCT_FAILURE',
}

export const initialDataConstants={
  GET_DATA_REQ: 'GET_DATA_REQ',
  GET_DATA_SUCCESS: 'GET_DATA_SUCCESS',
  GET_DATA_FAILURE: 'GET_DATA_FAILURE'
}